### PR TITLE
Adds department id to general ledger

### PR DESCRIPTION
**Pull request by MarcelloMolinaro**
**Are you a current Fivetran customer?** 

Yes!
Name: Marcello Molinaro
Title: Data Analyst
Company: Mozart Data

**What change(s) does this PR introduce?** 

This PR adds `department_id` to the `general_ledger` model. This allows for segmenting by `department_id` in the reporting layer (and joining on the `department` table to grab department `name` if desired).

**Did you update the CHANGELOG?** 

- [x] Yes

**Does this PR introduce a breaking change?**

- [x] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [x] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [x] No 

**How did you test the PR changes?** 

 

- [] CircleCi  
- [x] Local (please provide additional testing details below)
I ran `dbt seed` then `dbt test` in the integration tests directory. I also added department_id to the seed files. All tests ran successfully:
image
image

**Select which warehouse(s) were used to test the PR**
 

- [] BigQuery
- [] Redshift
- [x] Snowflake
- [] Postgres
- [] Databricks
- [] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:ocean:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

### CODE REVIEW

**Comment by MarcelloMolinaro** [comment]
Hey, just checking back in on this. I brought in the latest changes on this so it can be merged (a new version was pushed while I made this PR). I'm wondering if there's a timeline on something like this or if I can help with anything. Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @MarcelloMolinaro thanks so much for opening this PR and working to add more features!

The latest release was one that was needed to ensure the data for a number of customers was accurate. However, this PR would fit better with our next suite of breaking changes. If you would be able to, it would be great if you could rebase your branch off our `feature/quickbooks-updates-project` branch. This branch is intended to contain our next suite of breaking change updates.

If you rebase, we should be able to seamlessly review and merge your changes into our next updates.

**Comment by MarcelloMolinaro** [comment]
Hi @fivetran-joemarkiewicz ! I've rebased the PR 🎉 . I reran the integration tests and there were some tests that failed, but they appeared to be outside of the department_id commits that I made (`source_relation` and `class_id` errors). Please let me know if there's anything else you think you'll need from me.

image
image

**Comment by MarcelloMolinaro** [comment]
I'm seeing that my branch now has conflicts - Please let me know if you'd like me to re-base again. 
Per the above errors in testing, I had checked out the base branch and saw the same errors, so I don't believe that my changes introduced them.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @MarcelloMolinaro yes that would be great if you would be comfortable rebasing to `main`. We can actually take it from there if you are comfortable as a number of updates have rolled out into main that may require some adjustments on our end before merging in.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @MarcelloMolinaro just wanted to post back that we are still reviewing these updates and are going to work to integrate them into the next major release of the package.

I appreciate your patience with us working through this PR 😄

**Comment by MarcelloMolinaro** [comment]
Hey @fivetran-joemarkiewicz , I have now rebased my branch to main! 🎉 

As far as tests go, I don't believe that this PR added any new test failures. Running `dbt test` on `main` I saw the same test failures as I did after my changes. 

I think is ready to merge, please let me know if you need anything else!

**Comment by MarcelloMolinaro** [comment]
Hey again, just checking in on the status here to make sure I don't need to rebase again! Let me know if y'all need anything else.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @MarcelloMolinaro no need for you to rebase! We will plan to do a thorough review and rebase overhaul during our next major version upgrade to the QuickBooks package.

I do want to provide an update that the next major update won't be for a bit longer as a few other items have had to take priority. However, we have not forgotten about this PR! I will be sure to share an update here once we start working on the next major version upgrade to the package. When that time comes, this will undoubtedly be an invaluable piece of the upgrade!

Thank you again for taking the time to contribute this and I look forward to the next major update when we can fold this in 😄

**Review by fivetran-joemarkiewicz — APPROVED** [review]
@MarcelloMolinaro thank you again so much for contributing these updates to the package! I am currently working through a few other updates to the QuickBooks this package and will fold your addition to of the department_id to the GL into the next wave. You should see these live by the middle of next week, along with a few other updates!

**Pull request merged**
